security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/v1/api/login
            stateless: true
            json_login:
                check_path: /v1/api/login
                username_path: login
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/v1/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/v1/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/v1/api, roles: IS_AUTHENTICATED_FULLY }
